src/components/ftbot/BotStatus.vue
src/components/ftbot/FTBotAPIPairList.vue
src/store/modules/ftbot.js
src/views/Trade.vue

This component combines the whitelist and blacklist into one styled component and removes the text from the bot status which contains the whitelist and blacklist. 
I'm not sure If the vue lifecycle hooks are managed correctly, but it seems to work well even standalone without having to rely on the "refresh" methods -- Of course you will still need the "refresh" methods to update the pairlists if they are being dynamically generated, but I'm not sure if those methods should be inside this component or not?

Added pairlist component for better looking pairlists in UI.

---

.devcontainer/Dockerfile
.devcontainer/docker-compose.yml

When binding source directory it erase node_modules of the container. I have create a named volume   frequi-node-modules that is bind in a second time to ensure providing files.
What's new ?
- Fix the binding of node_modules to prevent to be empty
- Fix vue command not available

fix docker dev container node_modules binding

---

src/components/ftbot/TradeDetail.vue

As discussed in slack. Add headers in the tradedetail card to get a better overview of the trade details. I've also added the profit in pct.

Reorder trade details

---

src/components/ftbot/TradeDetail.vue

Some rates in the "Trade Detail" view were not using the formatPercent() helper and due to this, the view was trailing zeros.
- Use formatPercent() for all the rates in TradeDetail view
* Before (don't pay attention to the "Min Rate" as it chanched while I was taking the screen shot)
* After

Fix trailing zeros in TradeDetail view

---

Dockerfile
nginx.conf

Add support for routes loaded from URL.
For instance, the /dashboard route, when typed and loaded in the bar adress, returns a 404.
- Add support for routes loaded from URL.
- Add custom nginx config.
I added our custom Nginx config in the Dockerfile.
This config comes from the repo nginx:alpine, so it's the exact same config than before, but with this line added:
`try_files $uri /index.html;`
Which will redirect to index.html when no asset found.
Link to original nginx:alpine config: https://bitbucket.org/yobasystems/alpine-nginx/src/master/alpine-nginx-aarch64/files/nginx.conf

feat: add support for routes loaded from URL (custom nginx config)

---

src/components/charts/CumProfitChart.vue
src/components/charts/DailyChart.vue
src/components/layout/DraggableContainer.vue

Fixed the issue if the multi-pane list grows beyond the h-100 then overflow
closes #256 
- Added the overflow-auto at the card div which will ensure that card height would be limited to 100%
Result

multi-pane window to overflow after reaching the max height h-100 and adjust the chart labels

---

src/components/charts/TradesLog.vue

Change tradelog to barchart with color coding
closes #259

Change tradeslog to barchart

---

src/components/charts/CandleChart.vue

Goes to left or right end of the chart when the crosshairs/mouse passes over it, instead of just following the crosshairs.

make tooltip jump instead of follow

---

src/components/charts/CandleChart.vue

Set xAxis.axisPointer.label to false for main and subplots in CandleChart.vue
Helps to improve readability on charts
here are some pictures :
with dateTime labels :
without dateTime labels :

Remove axisPointer.label for chart readability

---

src/components/charts/TradesLog.vue

Some rearrangement in Trade Logs information box.
before :
pair | bot name
profit %
nn %
after : 
pair ( | bot name if exists)
trade close date
profit nn %

TradeLog info Box rearrengement

---

src/components/charts/CandleChart.vue
src/components/charts/CandleChartContainer.vue
src/shared/formatters.ts
src/shared/heikinashi.ts
src/types/types.ts

Add an option to show the dataset in Heikin Ashi format.
The formula is taken from: https://www.investopedia.com/terms/h/heikinashi.asp
If this option proves to be used often, having it in the current place makes it very accessible.
Otherwise, having it chart configuration modal might be better so everything is in one place.
Solve the issue: #560
- Add a checkbox on CandleChartContainer for an option to show the dataset in Heikin Ashi format
- Add a formatter that transforms dataset to Heikin Ashi format
*Explain in details what this PR solve or improve. You can include visuals.*

feat: heikin ashi format dataset

---

src/components/BotEntry.vue
src/components/BotList.vue
src/components/BotRename.vue
src/shared/userService.ts
src/store/modules/botStoreWrapper.ts
src/store/modules/ftbot/index.ts
src/types/auth.ts

Allow renaming bot name.
Closes #614
- Add Edit button on `BotEntry`
- Add `BotRename` component
- Add `renameBot` method on userService to handle the saving of the new name
- Add Vuex related stuff for renaming
Old idea:

feat: rename bot

---

.devcontainer/devcontainer.json

-> help to easy maintain *.drawio file in vscode dev container (frequi store diagram).
-> help to see color straight in editor  (src/components/BotEntry.vue:7)
- add drawio extension for vscode 
- add "color highlight" extension for vscode 
Improve developer experience
Have a nice day.

add vscode extensions (developer experience)

---

src/components/charts/CandleChart.vue
src/components/charts/CandleChartContainer.vue
src/components/ftbot/TradeListNav.vue
src/types/chart.ts
src/views/Backtesting.vue

Added column with trades for the selected pair in Visualize result and the ability to navigate to the selected trade on the chart. 
Solve the issue: #___
Not sure what to write here. 
The summary pretty much captures the details and the feature aims to improve productivity when going over trades while backtesting.
With open trades list:
https://prnt.sc/ssqwUKnsOH5Q
With collapsed trades list:
https://prnt.sc/ibY28wRNyWxF

Chart trade navigation

---

src/components/ftbot/PairSummary.vue
src/components/ftbot/TradeListNav.vue

After using trade navigation realized it would be handy to see if the trade was a long or a short at a glance as well.
For me it would be better to see the absolute combined profit for a pair in the list too. It does make it more cluttered looking, but useful information in my eyes. 
https://prnt.sc/oFN6ltxZModJ

Vis results modifications

---

src/shared/heikinashi.ts

This PR is intended to fix HaikinAshi calculation in Frequi graph.
rework on src/shared/heikinashi.ts
Those changes are intended to correct the way candle Open is calculeted.
actual method compute open candles based on the previous ohlcv candle and not the previous heikin ashi candle
based on the the links found in qtlibpy heikinashi method:
`
Heikin Ashi calculation: https://school.stockcharts.com/doku.php?id=chart_analysis:heikin_ashi
ha_open calculation based on: https://stackoverflow.com/a/55110393
ha_open = [ calculate first record ][ append remaining records with list comprehension method ]
list comprehension method is significantly faster as a for loop
`
and especially here for the 1st candle calculation: 
https://school.stockcharts.com/doku.php?id=chart_analysis:heikin_ashi#:~:text …

fix for heikin ashi calculation

---

src/components/ftbot/BotControls.vue
src/components/ftbot/ForceEntryForm.vue

Simple QOL improvement to use the selected pair of the active bot if the user doesn't type anything in the pair field.
At first shows as a placeholder so typing something else in would be convenient. If there isn't an active pair selected acts as previously did when left empty.

set pair to selectedPair if empty in force entry dialog

---

src/stores/plotConfig.ts

The delay I mean is the store getting updated via v-model after the change event is fired (In CandleChartContainer b-form-select), so there ends up being a wacky experience with the plot config dropdown (on first change nothing happens, on subsequent ones changing to the one that was the previous one selected). 
So this makes the UX how it should be.

fix select values updating with delay

---

src/components/ftbot/FreqaiModelSelect.vue
src/stores/ftbot.ts
src/types/backtest.ts
src/types/types.ts
src/views/Backtesting.vue

Add new options to efficiently backtest freqAI strategies.
https://github.com/freqtrade/freqtrade/pull/7923 must be included for this to show up.
* allow  backtsting of freqAI strategies via freqUI

Freqai backtest

---

src/components/ftbot/TradeListNav.vue

Added the ability to sort trades by newest or oldest first by clicking on the 'Trade Navigation' title in backtesting -> visualize result.
https://i.imgur.com/PzhUmng.png

Sorting in trade navigation

---

src/components/charts/CumProfitChart.vue

A quick fix for the 'Visualize summary" tab not working in v0.9.2 backtesting mode
Just import GridComponent into CumProfitChart component
No more console blocking error and graphs are showwing again :

Visualize summary

---

src/components/ftbot/TradeListNav.vue

Added the ability to see all filled orders for a trade in the trade navigation list, might be useful for others as well?
https://i.imgur.com/VvkLVt3.png

Ability to see orders in trade navigation

---

src/components/charts/CandleChart.vue
src/shared/charts/tradeChartData.ts

Show active stoploss for open trades
- Show stoploss line

Stop distance

---

src/components/charts/PlotConfigurator.vue

Noticed a bug when creating or duplicating a new plot config, and clicking save on that replaced the original config, instead of saving the new one.

fix selected plot config overwritten by new or duplicate

---

src/components/ftbot/BacktestResultComparison.vue
src/components/ftbot/BacktestRun.vue
src/components/ftbot/PairSummary.vue
src/components/ftbot/TradeListNav.vue
src/views/BacktestingView.vue

Add backtest comparison view 
- Add icons to backtest step selection
- Add Compare-results view (if more than 1 result is available)
-

Add backtest comparison view, allowing the comparison of multiple strategies

---

package.json
src/App.vue
src/auto-imports.d.ts
src/components/BotLogin.vue
src/components/BotRename.vue
src/components/charts/ProfitDistributionChart.vue
src/components/ftbot/ExchangeSelect.vue
src/components/general/BaseAlert.vue
src/main.ts
src/plugins/bootstrap-vue.ts
src/shared/alerts.ts
src/stores/alertsStore.ts
src/styles/_styles_ovw.scss
src/types/alertTypes.ts
yarn.lock

Work around design weaknesses in bootstrap-vue-next's "useToast" - so showing alerts / errors can be done from anywhere again.
- Bump bootstrap-vue-next to 0.16.1
- do necessary migration steps for update
- fix useToast usage

Fix broken use toast after bootstrap-vue-next update

---

src/components/ftbot/BotProfit.vue

Freq UI Trade view was incorrectly displaying `ROI open trades` with incorrect values. The correct metric to display is the `ROI closed trades` value.
This was solved by changing the metric name to `ROI closed trades` which is consistent with metrics on the Telegram `/profit` command and the metric on the dashboard.

fix(BotProfit.vue): fix incorrect ROI metric

---

README.md

There is no target in package.json defining install. Instead what is meant is the pnpm command 'install'
To correct an error in the readme regarding the command to install frequi's dependencies.
Solve the issue: # 1965
- See the readme
*Explain in details what this PR solve or improve. You can include visuals.*
A minor typographical, syntactical improvement.

pnpm run install -->  pnpm install. 

---

.github/workflows/ci.yml

Run CI against supported node versions.
21 ended support 6 months ago, and security support 4 months ago.
Add running CI against node 23.

chore: run ci against node 23, drop running against 21

---

src/components/charts/CandleChart.vue

When I select a trade in "Trade Navigation" (backtest visualize result), the trade is located in the chart "randomly" and sometimes outside the range. After some investigation, I found that the problem might be related to timezone. Let me explain it:
We pass the time with the format of "2024-01-01 01:00:00" (UTC) to ECharts, but according to [ECharts documentation](https://echarts.apache.org/en/option.html#series-line.data)
> a subset of [ISO 8601](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15), only including (all of these are treated as local time unless timezone is specified, which is consistent with [moment](https://momentjs.com/))
They are interpreted as in my local timezone (GMT+8)
So we might consider modifying the string format to something like …

Fix trade select

---

src/utils/randomColor.ts
tests/unit/randomColor.spec.ts

Fix for color generation function to not create colors from 5 characters for indicators

fix random color on minimal values

---

src/components/charts/PlotIndicator.vue

Fixes the color picker not including the `#` prefix on the hex colors which causes the chart to behave incorrect, for `line` type the color will be green and on chart hover the line will disappear, and on type `bar` the color will be incorrect but it wont disappear on hovering.
here is an example with a line type
and when hovering it
and here is how the bar type looks
Solve the issue: check if the value of the `xx.color` is a valid hex color value that doesn't have the `#` prefix and just add it in `xx.color`.

fix: Prepend '#' to the picked colors value missing the prefix

---

.github/workflows/ci.yml

Run tests against Node.js 24 and remove CI support for deprecated Node.js 18.

Update Node.js versions in CI configuration

---

package.json
pnpm-lock.yaml

Bump echarts and vue-echarts to 6.0.0 and 8.0.0-beta.2 respectively

chore: bump echarts to 6.0.0
